"""
常量模块
"""

# 互斥体名称
MUTEX_NAME = "Global\\D2R_MOD_JCY_MUTEX"

# 互斥错误 183, 表示互斥体已存在（即已有实例）
ERROR_ALREADY_EXISTS = 183

# 自定义消息ID(通知已有实例, restore窗口)
WM_SHOW_WINDOW = 0x5000

# 语言
ENUS = 'enUS'
ZHCN = 'zhCN'
ZHCN2 = 'zhCN2'
ZHTW = 'zhTW'
ZHTW2 = 'zhTW2'
ZHSGCN = "zhSGCN"
ZHSGTW = "zhSGTW"

LANGUAGES = [ZHCN2, ZHSGCN, ZHTW2, ZHSGTW, ENUS]

UI_PANEL_HEALTH = {"enUS":"Life:","zhTW":"生命：","deDE":"Leben:","esES":"Vida:","frFR":"Vie :","itIT":"Vita:","koKR":"생명력:","plPL":"Zdrowie:","esMX":"Vida:","jaJP":"ライフ:","ptBR":"Vida:","ruRU":"Здоровье:","zhCN":"生命:"}
UI_PANEL_MANA = {"enUS":"Mana:","zhTW":"法力：","deDE":"Mana:","esES":"Maná:","frFR":"Mana :","itIT":"Mana:","koKR":"마나:","plPL":"Mana:","esMX":"Maná:","jaJP":"マナ:","ptBR":"Mana:","ruRU":"Мана:","zhCN":"法力:"}

LANG = None

# 控制器名称
APP_NAME = "jcy控制器"

# MOD版本
APP_VERSION = "v1.3.7"

# 发布日期
APP_DATE = "20251226"

# 控制器全称
APP_FULL_NAME = f"{APP_NAME}_{APP_VERSION}"

# APP大小
APP_SIZE = "750x700"

# 区服地址
REGION_DOMAIN_MAP = {
    "kr": "kr.actual.battle.net",
    "us": "us.actual.battle.net",
    "eu": "eu.actual.battle.net"
}

# 区服名称
REGION_NAME_MAP = {
    "kr": "亚服",
    "us": "美服",
    "eu": "欧服"
}

# Unicode私有区字符 for 屏蔽道具
UE01A = "" * 41

# 全局字典
GLOBAL_DICT = {}

def init_global_dict(file_operations):
    GLOBAL_DICT.clear()
    GLOBAL_DICT.update(file_operations.load_global_dict())

def translate(text: str) -> str:
    """如果首位是 @ 则按字典翻译，否则原样返回"""
    if isinstance(text, str) and text.startswith('@'):
        key = text[1:]  # 去掉@
        _dict = GLOBAL_DICT.get(key)
        if _dict: 
            return _dict[ZHCN]
    return text

GOLD_NAMES = [
    {
        "Key": "gds",
        "enUS": "1-99 Gold",
        "zhCN": "1-99 金币",
        "zhTW": "1-99 金幣"
    },
    {
        "Key": "gdm",
        "enUS": "100-499 Gold",
        "zhCN": "100-499 金币",
        "zhTW": "100-499 金幣"
    },
    {
        "Key": "gdl",
        "enUS": "500-4999 Gold",
        "zhCN": "500-4999 金币",
        "zhTW": "500-4999 金幣"
    },
    {
        "Key": "gdx",
        "enUS": "5000+ Gold",
        "zhCN": "5000+ 金币",
        "zhTW": "5000+ 金幣"
    }
]

# <!-- Function Identifier 
NETEASE_LANGUAGE = "NeteaseLanguage"
BATTLE_NET_LANGUAGE = "BattleNetLanguage"
TERROR_ZONE_SERVER = "TerrorZoneServer"
TERROR_ZONE_LANGUAGE = "TerrorZoneLanguage"
TERROR_ZONE_NEXT = "TerrorZoneNext"
TERROR_ZONE_TABLE = "TerrorZoneTable"
GAME_SETTING = "GameSetting"
GAME_SETTING2 = "GameSetting2"
GAME_SETTING3 = "GameSetting3"
CONTROLS_SETTING = "ControlsSetting"
LIGHT_REDIUS = "LightRedius"
HUD_SIZE = "HudSize"
PORTAL_SKIN = "ProtalSkin"
CHARACTER_EFFECTS = "CharacterEffects"
ARROW = "Arrow"
SOR_SETTING = "SorceressSetting"
TELEPORT_SKIN = "TeleportSkin"
NEC_SETTING = "NecromancerSetting"
PAL_SETTING = "PaladinSetting"
BAR_SETTING = "BarbarianSetting"
DRU_SETTING = "DruidSetting"
ASN_SETTING = "AssassinSetting"
ASN_MARTIAL = "AssassinMartial"
COMMON_SETTING = "CommonSetting"
SKILL_OFF_SOUNDS = "SkillOffSounds"
MERCENARY = "Mercenary"
MERCENARY_LOCATION = "MercenaryLocation"
MERCENARY_100 = "Mercenary100"
MERCENARY_85 = "Mercenary85"
MERCENARY_75 = "Mercenary75"
MERCENARY_65 = "Mercenary65"
MONSTER_SETTING = "MonsterSetting"
MONSTER_LIGHTING = "MonsterLighting"
MONSTER_HEALTH = "MonsterHealth"
MONSTER_MISSILE = "MonsterMissile"
BASE_EFFECTS = "BaseEffects"
EQIUPMENT_SETTING = "EquipmentSetting"
AFFIX_EFFECTS = "AffixEffects"
UNIQUE_EFFECTS = "UniqueEffects"
SETS_EFFECTS = "SetsEffects"
UNIQUE_COLOR = "UniqueColor"
MODEL_EFFECTS = "ModelEffects"
RUNE_SIZE = "RuneSize"
ITEM_NOTIFICATION = "ItemNotification"
ITEM_RUNE_SETTING1 = "ItemRuneSetting1"
ITEM_RUNE_SETTING2 = "ItemRuneSetting2"
ASSET_PATH = "AssetPath"
DISABLE_EFFECTS = "DisableEffects"
ENABLE_POINTER = "EnablePointer"
TORCH_KEY = "TorchKey"
ITEM_FILTER = "ItemFilter"
WAYPOINT_POINTER = "WayPointPointer"
MISSION_POINTER = "MissionPointer"
UPSTAIRS_POINTER = "UpstairsPointer"
DOWNSTAIRS_POINTER = "DownstairsPointer"
NEXTAREA_POINTER = "NextareaPointer"
MINI_CUBE = "MiniCube"
ESC_SETTING = "EscSetting"
# Function Identifier -->

# Assets
GAME_MODEL = "GameModel"
RUNE_SKIN = "RuneSkin"
SKILL_SKIN = "SkillSkin"
FONT_TYPE = "FontType"
ACT1_HIRE = "Act1Hire"
ACT2_HIRE = "Act2Hire"
ACT3_HIRE = "Act3Hire"
ACT5_HIRE = "Act5Hire"
HUD_SKIN = "HudSkin"
OTHERS = "Others"
TOA = "Token of Absolution"

AMA = "Ama"
SOR = "Sor"
NEC = "Nec"
PAL = "Pal"
BAR = "Bar"
DRU = "Sor"
ASN = "Asn"

APPLY_METHOD = "apply_method"
REMOVE_METHOD = "remove_method"
GAME_MODEL_APPLY = "game_model_apply"
HIRE_SKIN_APPLY = "hire_skin_apply"
HIRE_SKIN_REMOVE = "hire_skin_remove"



# <!-- Controller Type
RADIO = "RadioGroup"
CHECK = "CheckGroup"
SPIN = "SpinBox"
SEPARATOR = "Separator"
LOCATION = "Location"
# Controller Type -->

ITEM_ENUS = ["El Rune", "Eld Rune", "Tir Rune", "Nef Rune", "Eth Rune", "Ith Rune", "Tal Rune", "Ral Rune", "Ort Rune", "Thul Rune", "Amn Rune", "Sol Rune", "Shael Rune", "Dol Rune", "Hel Rune", "Io Rune", "Lum Rune", "Ko Rune", "Fal Rune", "Lem Rune", "Pul Rune", "Um Rune", "Mal Rune", "Ist Rune", "Gul Rune", "Vex Rune", "Ohm Rune", "Lo Rune", "Sur Rune", "Ber Rune", "Jah Rune", "Cham Rune", "Zod Rune", "Ring", "Amulet", "Jewel", "Small Charm", "Large Charm", "Grand Charm", "Diadem"]
ITEM_ZHTW = ["艾爾#01", "艾德#02", "特爾#03", "那夫#04", "愛斯#05", "伊司#06", "塔爾#07", "拉爾#08", "歐特#09", "書爾#10", "安姆#11", "索爾#12", "夏#13", "多爾#14", "海爾#15", "埃歐#16", "盧姆#17", "科#18", "法爾#19", "藍姆#20", "普爾#21", "烏姆#22", "馬爾#23", "伊司特#24", "古爾#25", "伐克斯#26", "歐姆#27", "羅#28", "瑟#29", "貝#30", "喬#31", "查姆#32", "薩德#33", "戒指", "項鏈", "珠寶", "小型咒符", "大型咒符", "巨型咒符", "權冠"]
# 本地化文件列表
LNG_STRINGS = [
    r"data/local/lng/strings/item-gems.json",
    r"data/local/lng/strings/item-modifiers.json",
    r"data/local/lng/strings/item-nameaffixes.json",
    r"data/local/lng/strings/item-names.json",
    r"data/local/lng/strings/item-runes.json",
    r"data/local/lng/strings/levels.json",
    r"data/local/lng/strings/monsters.json",
    r"data/local/lng/strings/npcs.json",
    r"data/local/lng/strings/objects.json",
    r"data/local/lng/strings/quests.json",
    r"data/local/lng/strings/shrines.json",
    r"data/local/lng/strings/skills.json",
]

# 恐怖区域API
TERROR_ZONE_API = {
    "1" : ["https://asia.d2tz.info/terror_zone?mode=online", "https://api.d2tz.info/terror_zone?mode=online"],
    "2": ["https://api.d2-trade.com.cn/api/query/tz_online/zh-cn"],
}

# 恐怖地带
TERROR_ZONE_DICT = {
  "0-0": {"zhCN": "解析失败, 通知作者", "zhTW": "解析失敗, 通知作者", "enUS": "Parse Failed, Tip Author", "exp": "-", "drop": "-"},
  "1-1": {"zhCN": "鲜血荒地、 邪恶洞穴", "zhTW": "鮮血荒地、 邪惡洞窟", "enUS": "Blood Moor, Den of Evil", "exp": "F", "drop": "F"},
  "1-2": {"zhCN": "冰冷之原、洞穴", "zhTW": "冰冷之原、洞穴", "enUS": "Cold Plains, The Cave", "exp": "C", "drop": "D"},
  "1-3": {"zhCN": "埋骨之地、墓穴、寝陵", "zhTW": "埋骨之地、墓穴、大陵墓", "enUS": "Burial Grounds, The Crypt, The Mausoleum", "exp": "F", "drop": "F"},
  "1-4": {"zhCN": "石块旷野", "zhTW": "亂石曠野", "enUS": "Stony Field", "exp": "F", "drop": "D"},
  "1-5": {"zhCN": "崔斯特姆", "zhTW": "崔斯特姆", "enUS": "Tristram", "exp": "F", "drop": "F"},
  "1-6": {"zhCN": "黑暗森林、地下通道", "zhTW": "黑暗森林、地底通道", "enUS": "Dark Wood, Underground Passage", "exp": "C", "drop": "D"},
  "1-7": {"zhCN": "黑色沼泽、 洞坑", "zhTW": "黑色荒地、 地洞", "enUS": "Black Marsh, The Hole", "exp": "C", "drop": "D"},
  "1-8": {"zhCN": "被遗忘的高塔", "zhTW": "遺忘之塔", "enUS": "The Forgotten Tower", "exp": "C", "drop": "A"},
  "1-9": {"zhCN": "深坑", "zhTW": "地穴", "enUS": "The Pit", "exp": "A", "drop": "A"},
  "1-10": {"zhCN": "监牢、营房", "zhTW": "監牢、兵營", "enUS": "Jail, Barracks", "exp": "B", "drop": "C"},
  "1-11": {"zhCN": "大教堂、地下墓穴", "zhTW": "大教堂、地下墓穴", "enUS": "Cathedral, Catacombs", "exp": "A", "drop": "A"},
  "1-12": {"zhCN": "哞哞农场", "zhTW": "哞哞農場", "enUS": "Moo Moo Farm", "exp": "B", "drop": "S"},
  "2-1": {"zhCN": "下水道", "zhTW": "鲁高因下水道", "enUS": "Lut Gholein Sewers", "exp": "B", "drop": "C"},
  "2-2": {"zhCN": "碎石荒野、碎石古墓", "zhTW": "碎石荒地、古老石墓", "enUS": "Rocky Waste, Stony Tomb", "exp": "B", "drop": "C"},
  "2-3": {"zhCN": "干燥高地、亡者大殿", "zhTW": "乾土高地、死亡之殿", "enUS": "Dry Hills, Halls of the Dead", "exp": "A", "drop": "C"},
  "2-4": {"zhCN": "偏远绿洲", "zhTW": "遙遠的綠洲", "enUS": "Far Oasis", "exp": "F", "drop": "F"},
  "2-5": {"zhCN": "古代水道", "zhTW": "古代通道", "enUS": "Ancient Tunnels", "exp": "D", "drop": "C"},
  "2-6": {"zhCN": "失落之城、群蛇峡谷、利爪蝮蛇神殿", "zhTW": "失落古城、群蛇峽谷、利爪蛇魔神殿", "enUS": "Lost City, Valley of Snakes, Claw Viper Temple", "exp": "C", "drop": "C"},
  "2-7": {"zhCN": "神秘避难所", "zhTW": "秘法聖殿", "enUS": "Arcane Sanctuary", "exp": "C", "drop": "A"},
  "2-8": {"zhCN": "塔•拉夏之墓、塔•拉夏的墓室", "zhTW": "塔拉夏的古墓、塔拉夏的密室", "enUS": "Tal Rasha's Tombs, Tal Rasha's Chamber", "exp": "S", "drop": "A"},
  "3-1": {"zhCN": "蜘蛛森林、蜘蛛洞穴", "zhTW": "蜘蛛森林、蜘蛛洞窟", "enUS": "Spider Forest, Spider Cavern", "exp": "C", "drop": "B"},
  "3-2": {"zhCN": "剥皮魔丛林、剥皮魔监牢", "zhTW": "剝皮叢林、剝皮地牢", "enUS": "Flayer Jungle, Flayer Dungeon", "exp": "A", "drop": "B"},
  "3-3": {"zhCN": "庞大湿地", "zhTW": "大沼澤", "enUS": "Great Marsh", "exp": "C", "drop": "B"},
  "3-4": {"zhCN": "库拉斯特集市、毁灭的神庙、废弃的礼拜堂", "zhTW": "庫拉斯特市集、荒廢的神殿、廢棄的寺院", "enUS": "Kurast Bazaar, Ruined Temple, Disused Fane", "exp": "C", "drop": "B"},
  "3-5": {"zhCN": "崔凡克", "zhTW": "崔凡克", "enUS": "Travincal", "exp": "B", "drop": "A"},
  "3-6": {"zhCN": "憎恨囚牢", "zhTW": "憎恨的囚牢", "enUS": "Durance of Hate", "exp": "C", "drop": "A"},
  "4-1": {"zhCN": "外围荒原、绝望平原", "zhTW": "外圍荒原、絕望平原", "enUS": "Outer Steppes, Plains of Despair", "exp": "C", "drop": "C"},
  "4-2": {"zhCN": "火焰之河、神罚之城", "zhTW": "火焰之河、罪罰之城", "enUS": "River of Flame, City of the Damned", "exp": "B", "drop": "B"},
  "4-3": {"zhCN": "混沌避难所", "zhTW": "混沌庇難所", "enUS": "Chaos Sanctuary", "exp": "S", "drop": "S"},
  "5-1": {"zhCN": "血腥丘陵、冰冻高地、亚巴顿", "zhTW": "血腥丘陵、冰凍高地、亞巴頓", "enUS": "Bloody Foothills, Frigid Highlands, Abaddon", "exp": "B", "drop": "B"},
  "5-2": {"zhCN": "冰川小径、漂流洞窟", "zhTW": "冰河小径、漂泊者洞窟", "enUS": "Glacial Trail, Drifter Cavern", "exp": "C", "drop": "C"},
  "5-3": {"zhCN": "先祖之路、寒冰地窖", "zhTW": "先祖之路、冰窖", "enUS": "Ancient's Way, Icy Cellar", "exp": "C", "drop": "C"},
  "5-4": {"zhCN": "亚瑞特高原、阿克隆深渊", "zhTW": "亞瑞特高原、冥河地穴", "enUS": "Arreat Plateau, Pit of Acheron", "exp": "B", "drop": "C"},
  "5-5": {"zhCN": "水晶通道、冰冻之河", "zhTW": "水晶通道、冰凍之河", "enUS": "Crystalline Passage, Frozen River", "exp": "C", "drop": "C"},
  "5-6": {"zhCN": "尼拉塞克的神殿、痛楚大厅、苦痛大厅、沃特大厅", "zhTW": "尼拉塞克神殿、怨慟之廳、苦痛之廳、沃特之廳", "enUS": "Nihlathak's Temple, Temple Halls", "exp": "B", "drop": "A"},
  "5-7": {"zhCN": "世界之石要塞、毁灭王座、世界之石大殿", "zhTW": "世界之石要塞、毀滅王座、世界之石大殿", "enUS": "Worldstone Keep, Throne of Destruction, Worldstone Chamber", "exp": "S", "drop": "S"}
}

TERROR_ZONE_MAP = {
    "精华荒地":"1-1",
    "鮮血荒地":"1-1",
    "鲜红荒地":"1-1",
    "邪恶洞穴":"1-1",
    "邪惡洞窟":"1-1",
    "冰冷之原":"1-2",
    "洞穴":"1-2",
    "埋骨之地":"1-3",
    "墓穴":"1-3",
    "墓地":"1-3",
    "大陵墓":"1-3",
    "寝陵":"1-3",
    "石块旷野":"1-4",
    "亂石曠野":"1-4",
    "崔斯特姆":"1-5",
    "黑暗森林":"1-6",
    "地底通道":"1-6",
    "地下通道":"1-6",
    "黑色沼泽":"1-7",
    "黑色荒地":"1-7",
    "地洞":"1-7",
    "被遗忘的高塔":"1-8",
    "遺忘之塔":"1-8",
    "地穴":"1-9",
    "深坑":"1-9",
    "监狱":"1-10",
    "監牢":"1-10",
    "兵營":"1-10",
    "营房":"1-10",
    "大教堂":"1-11",
    "地下墓穴":"1-11",
    "秘密乳牛關":"1-12",
    "神秘的奶牛关":"1-12",
    "下水道":"2-1",
    "鲁高因下水道":"2-1",
    "鲁·高因下水道":"2-1",
    "碎石荒野":"2-2",
    "碎石荒地":"2-2",
    "古老石墓":"2-2",
    "碎石古墓":"2-2",
    "乾土高地":"2-3",
    "干燥高地":"2-3",
    "死亡之殿":"2-3",
    "亡者大殿":"2-3",
    "遙遠的綠洲":"2-4",
    "偏远绿洲":"2-4",
    "古代通道":"2-5",
    "古代水道":"2-5",
    "失落古城":"2-6",
    "失落之城":"2-6",
    "群蛇峽谷":"2-6",
    "群蛇峡谷":"2-6",
    "利爪蛇魔神殿":"2-6",
    "利爪蝮蛇神殿":"2-6",
    "秘法聖殿":"2-7",
    "神秘避难所":"2-7",
    "塔拉夏的古墓":"2-8",
    "塔·拉夏之墓":"2-8",
    "塔拉夏的密室":"2-8",
    "塔·拉夏的墓室":"2-8",
    "蜘蛛森林":"3-1",
    "蜘蛛洞窟":"3-1",
    "蜘蛛洞穴":"3-1",
    "剝皮叢林":"3-2",
    "翠绿丛林":"3-2",
    "剝皮地牢":"3-2",
    "翠绿监牢":"3-2",
    "大沼澤":"3-3",
    "庞大湿地":"3-3",
    "庫拉斯特市集":"3-4",
    "库拉斯特集市":"3-4",
    "荒廢的神殿":"3-4",
    "毁灭的神庙":"3-4",
    "廢棄的寺院":"3-4",
    "废弃的礼拜堂":"3-4",
    "崔凡克":"3-5",
    "憎恨囚牢":"3-6",
    "外圍荒原":"4-1",
    "外域荒原":"4-1",
    "絕望平原":"4-1",
    "绝望平原":"4-1",
    "火焰之河":"4-2",
    "罪罰之城":"4-2",
    "神罚之城":"4-2",
    "混沌魔殿":"4-3",
    "混沌避难所":"4-3",
    "血腥丘陵":"5-1",
    "嗜战丘陵":"5-1",
    "苦战丘陵":"5-1",
    "冰凍高地":"5-1",
    "冰冻高地":"5-1",
    "亞巴頓":"5-1",
    "亚巴顿":"5-1",
    "冰河小徑":"5-2",
    "冰川小径":"5-2",
    "漂泊者洞窟":"5-2",
    "漂流洞窟":"5-2",
    "先祖之路":"5-3",
    "冰窖":"5-3",
    "寒冰地窖":"5-3",
    "亞瑞特高原":"5-4",
    "亚瑞特高原":"5-4",
    "冥河地穴":"5-4",
    "阿克隆深渊":"5-4",
    "水晶通道":"5-5",
    "冰凍之河":"5-5",
    "冰冻之河":"5-5",
    "尼拉塞克的神殿":"5-6",
    "怨慟之廳":"5-6",
    "痛楚大厅":"5-6",
    "苦痛之廳":"5-6",
    "苦痛大厅":"5-6",
    "沃特之廳":"5-6",
    "沃特大厅":"5-6",
    "世界之石要塞":"5-7",
    "毀滅王座":"5-7",
    "毁灭王座":"5-7",
    "世界之石大殿":"5-7"
}

# SETS_INDEX
SETS_INDEX = [
  "Civerb's Vestments",
  "Hsarus' Defense",
  "Cleglaw's Brace",
  "Iratha's Finery",
  "Isenhart's Armory",
  "Vidala's Rig",
  "Milabrega's Regalia",
  "Cathan's Traps",
  "Tancred's Battlegear",
  "Sigon's Complete Steel",
  "Infernal Tools",
  "Berserker's Garb",
  "Death's Disguise",
  "Angelical Raiment",
  "Arctic Gear",
  "Arcanna's Tricks",
  "Natalya's Odium",
  "Aldur's Watchtower",
  "Immortal King",
  "Tal Rasha's Wrappings",
  "Griswold's Legacy",
  "Trang-Oul's Avatar",
  "M'avina's Battle Hymn",
  "The Disciple",
  "Heaven's Brethren",
  "Orphan's Call",
  "Hwanin's Majesty",
  "Sazabi's Grand Tribute",
  "Bul-Kathos' Children",
  "Cow King's Leathers",
  "Naj's Ancient Set",
  "McAuley's Folly",
  "Warlord's Glory",
]

# SetItemIndex
SET_ITEM_INDEX = [
  "Civerb's Ward",
  "Civerb's Icon",
  "Civerb's Cudgel",
  "Hsarus' Iron Heel",
  "Hsarus' Iron Fist",
  "Hsarus' Iron Stay",
  "Cleglaw's Tooth",
  "Cleglaw's Claw",
  "Cleglaw's Pincers",
  "Iratha's Collar",
  "Iratha's Cuff",
  "Iratha's Coil",
  "Iratha's Cord",
  "Isenhart's Lightbrand",
  "Isenhart's Parry",
  "Isenhart's Case",
  "Isenhart's Horns",
  "Vidala's Barb",
  "Vidala's Fetlock",
  "Vidala's Ambush",
  "Vidala's Snare",
  "Milabrega's Orb",
  "Milabrega's Rod",
  "Milabrega's Diadem",
  "Milabrega's Robe",
  "Cathan's Rule",
  "Cathan's Mesh",
  "Cathan's Visage",
  "Cathan's Sigil",
  "Cathan's Seal",
  "Tancred's Crowbill",
  "Tancred's Spine",
  "Tancred's Hobnails",
  "Tancred's Weird",
  "Tancred's Skull",
  "Sigon's Gage",
  "Sigon's Visor",
  "Sigon's Shelter",
  "Sigon's Sabot",
  "Sigon's Wrap",
  "Sigon's Guard",
  "Infernal Cranium",
  "Infernal Torch",
  "Infernal Sign",
  "Berserker's Headgear",
  "Berserker's Hauberk",
  "Berserker's Hatchet",
  "Death's Hand",
  "Death's Guard",
  "Death's Touch",
  "Angelic Sickle",
  "Angelic Mantle",
  "Angelic Halo",
  "Angelic Wings",
  "Arctic Horn",
  "Arctic Furs",
  "Arctic Binding",
  "Arctic Mitts",
  "Arcanna's Sign",
  "Arcanna's Deathwand",
  "Arcanna's Head",
  "Arcanna's Flesh",
  "Expansion",
  "Natalya's Totem",
  "Natalya's Mark",
  "Natalya's Shadow",
  "Natalya's Soul",
  "Aldur's Stony Gaze",
  "Aldur's Deception",
  "Aldur's Gauntlet",
  "Aldur's Advance",
  "Immortal King's Will",
  "Immortal King's Soul Cage",
  "Immortal King's Detail",
  "Immortal King's Forge",
  "Immortal King's Pillar",
  "Immortal King's Stone Crusher",
  "Tal Rasha's Fire-Spun Cloth",
  "Tal Rasha's Adjudication",
  "Tal Rasha's Lidless Eye",
  "Tal Rasha's Howling Wind",
  "Tal Rasha's Horadric Crest",
  "Griswold's Valor",
  "Griswold's Heart",
  "Griswolds's Redemption",
  "Griswold's Honor",
  "Trang-Oul's Guise",
  "Trang-Oul's Scales",
  "Trang-Oul's Wing",
  "Trang-Oul's Claws",
  "Trang-Oul's Girth",
  "M'avina's True Sight",
  "M'avina's Embrace",
  "M'avina's Icy Clutch",
  "M'avina's Tenet",
  "M'avina's Caster",
  "Telling of Beads",
  "Laying of Hands",
  "Rite of Passage",
  "Spiritual Custodian",
  "Credendum",
  "Dangoon's Teaching",
  "Heaven's Taebaek",
  "Haemosu's Adament",
  "Ondal's Almighty",
  "Guillaume's Face",
  "Wilhelm's Pride",
  "Magnus' Skin",
  "Wihtstan's Guard",
  "Hwanin's Splendor",
  "Hwanin's Refuge",
  "Hwanin's Seal",
  "Hwanin's Justice",
  "Sazabi's Cobalt Redeemer",
  "Sazabi's Ghost Liberator",
  "Sazabi's Mental Sheath",
  "Bul-Kathos' Sacred Charge",
  "Bul-Kathos' Tribal Guardian",
  "Cow King's Horns",
  "Cow King's Hide",
  "Cow King's Hoofs",
  "Naj's Puzzler",
  "Naj's Light Plate",
  "Naj's Circlet",
  "McAuley's Paragon",
  "McAuley's Riprap",
  "McAuley's Taboo",
  "McAuley's Superstition",
  "Warlord's Conquest",
  "Warlord's Lust",
  "Warlord's Mantle",
  "Warlord's Crushers",
  "Warlord's Authority",
]

# 装备底材
ITEM_BASE = [
    "2ax",
    "2hs",
    "6bs",
    "6cb",
    "6cs",
    "6hb",
    "6hx",
    "6l7",
    "6lb",
    "6ls",
    "6lw",
    "6lx",
    "6mx",
    "6rx",
    "6s7",
    "6sb",
    "6ss",
    "6sw",
    "6ws",
    "72a",
    "72h",
    "7ar",
    "7ax",
    "7b7",
    "7b8",
    "7ba",
    "7bk",
    "7bl",
    "7br",
    "7bs",
    "7bt",
    "7bw",
    "7cl",
    "7cm",
    "7cr",
    "7cs",
    "7dg",
    "7di",
    "7fb",
    "7fc",
    "7fl",
    "7ga",
    "7gd",
    "7gi",
    "7gl",
    "7gm",
    "7gs",
    "7gw",
    "7h7",
    "7ha",
    "7ja",
    "7kr",
    "7la",
    "7ls",
    "7lw",
    "7m7",
    "7ma",
    "7mp",
    "7mt",
    "7o7",
    "7p7",
    "7pa",
    "7pi",
    "7qr",
    "7qs",
    "7s7",
    "7s8",
    "7sb",
    "7sc",
    "7sm",
    "7sp",
    "7sr",
    "7ss",
    "7st",
    "7ta",
    "7tk",
    "7tr",
    "7ts",
    "7tw",
    "7vo",
    "7wa",
    "7wb",
    "7wc",
    "7wd",
    "7wh",
    "7wn",
    "7ws",
    "7xf",
    "7yw",
    "8bs",
    "8cb",
    "8cs",
    "8hb",
    "8hx",
    "8l8",
    "8lb",
    "8ls",
    "8lw",
    "8lx",
    "8mx",
    "8rx",
    "8s8",
    "8sb",
    "8ss",
    "8sw",
    "8ws",
    "92a",
    "92h",
    "9ar",
    "9ax",
    "9b7",
    "9b8",
    "9b9",
    "9ba",
    "9bk",
    "9bl",
    "9br",
    "9bs",
    "9bt",
    "9bw",
    "9cl",
    "9cm",
    "9cr",
    "9cs",
    "9dg",
    "9di",
    "9fb",
    "9fc",
    "9fl",
    "9ga",
    "9gd",
    "9gi",
    "9gl",
    "9gm",
    "9gs",
    "9gw",
    "9h9",
    "9ha",
    "9ja",
    "9kr",
    "9la",
    "9ls",
    "9lw",
    "9m9",
    "9ma",
    "9mp",
    "9mt",
    "9p9",
    "9pa",
    "9pi",
    "9qr",
    "9qs",
    "9s8",
    "9s9",
    "9sb",
    "9sc",
    "9sm",
    "9sp",
    "9sr",
    "9ss",
    "9st",
    "9ta",
    "9tk",
    "9tr",
    "9ts",
    "9tw",
    "9vo",
    "9wa",
    "9wb",
    "9wc",
    "9wd",
    "9wh",
    "9wn",
    "9ws",
    "9xf",
    "9yw",
    "aar",
    "am1",
    "am2",
    "am3",
    "am4",
    "am5",
    "am6",
    "am7",
    "am8",
    "am9",
    "ama",
    "amb",
    "amc",
    "amd",
    "ame",
    "amf",
    "axe",
    "axf",
    "ba1",
    "ba2",
    "ba3",
    "ba4",
    "ba5",
    "ba6",
    "ba7",
    "ba8",
    "ba9",
    "baa",
    "bab",
    "bac",
    "bad",
    "bae",
    "baf",
    "bal",
    "bar",
    "bax",
    "bhm",
    "bkf",
    "bld",
    "brn",
    "brs",
    "bsd",
    "bsh",
    "bst",
    "bsw",
    "btl",
    "btx",
    "buc",
    "bwn",
    "cap",
    "cbw",
    "ces",
    "chn",
    "ci0",
    "ci1",
    "ci2",
    "ci3",
    "clb",
    "clm",
    "clw",
    "crn",
    "crs",
    "cst",
    "dgr",
    "dir",
    "dr1",
    "dr2",
    "dr3",
    "dr4",
    "dr5",
    "dr6",
    "dr7",
    "dr8",
    "dr9",
    "dra",
    "drb",
    "drc",
    "drd",
    "dre",
    "drf",
    "fhl",
    "fla",
    "flb",
    "flc",
    "fld",
    "ful",
    "gax",
    "ghm",
    "gis",
    "gix",
    "glv",
    "gma",
    "gsc",
    "gsd",
    "gth",
    "gts",
    "gwn",
    "hal",
    "hax",
    "hbl",
    "hbt",
    "hbw",
    "hgl",
    "hla",
    "hlm",
    "hxb",
    "jav",
    "kit",
    "kri",
    "ktr",
    "lax",
    "lbb",
    "lbl",
    "lbt",
    "lbw",
    "lea",
    "lgl",
    "lrg",
    "lsd",
    "lst",
    "ltp",
    "lwb",
    "lxb",
    "mac",
    "mau",
    "mbl",
    "mbt",
    "mgl",
    "mpi",
    "msk",
    "mst",
    "mxb",
    "ne1",
    "ne2",
    "ne3",
    "ne4",
    "ne5",
    "ne6",
    "ne7",
    "ne8",
    "ne9",
    "nea",
    "neb",
    "ned",
    "nee",
    "nef",
    "neg",
    "ob1",
    "ob2",
    "ob3",
    "ob4",
    "ob5",
    "ob6",
    "ob7",
    "ob8",
    "ob9",
    "oba",
    "obb",
    "obc",
    "obd",
    "obe",
    "obf",
    "pa1",
    "pa2",
    "pa3",
    "pa4",
    "pa5",
    "pa6",
    "pa7",
    "pa8",
    "pa9",
    "paa",
    "pab",
    "pac",
    "pad",
    "pae",
    "paf",
    "pax",
    "pik",
    "pil",
    "plt",
    "qui",
    "rng",
    "rxb",
    "sbb",
    "sbr",
    "sbw",
    "scl",
    "scm",
    "scp",
    "scy",
    "skp",
    "skr",
    "sml",
    "spc",
    "spk",
    "spl",
    "spr",
    "spt",
    "ssd",
    "ssp",
    "sst",
    "stu",
    "swb",
    "tax",
    "tbl",
    "tbt",
    "tgl",
    "tkf",
    "tow",
    "tri",
    "tsp",
    "uap",
    "uar",
    "ucl",
    "uea",
    "uh9",
    "uhb",
    "uhc",
    "uhg",
    "uhl",
    "uhm",
    "uhn",
    "uit",
    "ukp",
    "ula",
    "ulb",
    "ulc",
    "uld",
    "ulg",
    "ulm",
    "ult",
    "umb",
    "umc",
    "umg",
    "uml",
    "ung",
    "uow",
    "upk",
    "upl",
    "urg",
    "urn",
    "urs",
    "ush",
    "usk",
    "utb",
    "utc",
    "utg",
    "uth",
    "utp",
    "uts",
    "utu",
    "uuc",
    "uui",
    "uul",
    "uvb",
    "uvc",
    "uvg",
    "vbl",
    "vbt",
    "vgl",
    "vou",
    "wax",
    "whm",
    "wnd",
    "wrb",
    "wsc",
    "wsd",
    "wsp",
    "wst",
    "xap",
    "xar",
    "xcl",
    "xea",
    "xh9",
    "xhb",
    "xhg",
    "xhl",
    "xhm",
    "xhn",
    "xit",
    "xkp",
    "xla",
    "xlb",
    "xld",
    "xlg",
    "xlm",
    "xlt",
    "xmb",
    "xmg",
    "xml",
    "xng",
    "xow",
    "xpk",
    "xpl",
    "xrg",
    "xrn",
    "xrs",
    "xsh",
    "xsk",
    "xtb",
    "xtg",
    "xth",
    "xtp",
    "xts",
    "xtu",
    "xuc",
    "xui",
    "xul",
    "xvb",
    "xvg",
    "ywn",
    "zhb",
    "zlb",
    "zmb",
    "ztb",
    "zvb"
]

# 装备-暗金
ITEM_UNIQUE = [
    "The Gnasher",
    "Deathspade",
    "Bladebone",
    "Mindrend",
    "Rakescar",
    "Fechmars Axe",
    "Goreshovel",
    "The Chieftan",
    "Brainhew",
    "The Humongous",
    "Iros Torch",
    "Maelstromwrath",
    "Gravenspine",
    "Umes Lament",
    "Felloak",
    "Knell Striker",
    "Rusthandle",
    "Stormeye",
    "Stoutnail",
    "Crushflange",
    "Bloodrise",
    "The Generals Tan Do Li Ga",
    "Ironstone",
    "Bonesob",
    "Steeldriver",
    "Rixots Keen",
    "Blood Crescent",
    "Krintizs Skewer",
    "Gleamscythe",
    "Azurewrath",
    "Griswolds Edge",
    "Hellplague",
    "Culwens Point",
    "Shadowfang",
    "Soulflay",
    "Kinemils Awl",
    "Blacktongue",
    "Ripsaw",
    "The Patriarch",
    "Gull",
    "The Diggler",
    "The Jade Tan Do",
    "Irices Shard",
    "The Dragon Chang",
    "Razortine",
    "Bloodthief",
    "Lance of Yaggai",
    "The Tannr Gorerod",
    "Dimoaks Hew",
    "Steelgoad",
    "Soul Harvest",
    "The Battlebranch",
    "Woestave",
    "The Grim Reaper",
    "Bane Ash",
    "Serpent Lord",
    "Lazarus Spire",
    "The Salamander",
    "The Iron Jang Bong",
    "Pluckeye",
    "Witherstring",
    "Rimeraven",
    "Piercerib",
    "Pullspite",
    "Wizendraw",
    "Hellclap",
    "Blastbark",
    "Leadcrow",
    "Ichorsting",
    "Hellcast",
    "Doomspittle",
    "War Bonnet",
    "Tarnhelm",
    "Coif of Glory",
    "Duskdeep",
    "Wormskull",
    "Howltusk",
    "Undead Crown",
    "The Face of Horror",
    "Greyform",
    "Blinkbats Form",
    "The Centurion",
    "Twitchthroe",
    "Darkglow",
    "Hawkmail",
    "Sparking Mail",
    "Venomsward",
    "Iceblink",
    "Boneflesh",
    "Rockfleece",
    "Rattlecage",
    "Goldskin",
    "Victors Silk",
    "Heavenly Garb",
    "Pelta Lunata",
    "Umbral Disk",
    "Stormguild",
    "Wall of the Eyeless",
    "Swordback Hold",
    "Steelclash",
    "Bverrit Keep",
    "The Ward",
    "The Hand of Broc",
    "Bloodfist",
    "Chance Guards",
    "Magefist",
    "Frostburn",
    "Hotspur",
    "Gorefoot",
    "Treads of Cthon",
    "Goblin Toe",
    "Tearhaunch",
    "Lenyms Cord",
    "Snakecord",
    "Nightsmoke",
    "Goldwrap",
    "Bladebuckle",
    "Nokozan Relic",
    "The Eye of Etlich",
    "The Mahim-Oak Curio",
    "Nagelring",
    "Manald Heal",
    "The Stone of Jordan",
    "Amulet of the Viper",
    "Staff of Kings",
    "Horadric Staff",
    "Hell Forge Hammer",
    "KhalimFlail",
    "SuperKhalimFlail",
    "Expansion",
    "Coldkill",
    "Butcher's Pupil",
    "Islestrike",
    "Pompe's Wrath",
    "Guardian Naga",
    "Warlord's Trust",
    "Spellsteel",
    "Stormrider",
    "Boneslayer Blade",
    "The Minataur",
    "Suicide Branch",
    "Carin Shard",
    "Arm of King Leoric",
    "Blackhand Key",
    "Dark Clan Crusher",
    "Zakarum's Hand",
    "The Fetid Sprinkler",
    "Hand of Blessed Light",
    "Fleshrender",
    "Sureshrill Frost",
    "Moonfall",
    "Baezil's Vortex",
    "Earthshaker",
    "Bloodtree Stump",
    "The Gavel of Pain",
    "Bloodletter",
    "Coldsteel Eye",
    "Hexfire",
    "Blade of Ali Baba",
    "Ginther's Rift",
    "Headstriker",
    "Plague Bearer",
    "The Atlantian",
    "Crainte Vomir",
    "Bing Sz Wang",
    "The Vile Husk",
    "Cloudcrack",
    "Todesfaelle Flamme",
    "Swordguard",
    "Spineripper",
    "Heart Carver",
    "Blackbog's Sharp",
    "Stormspike",
    "The Impaler",
    "Kelpie Snare",
    "Soulfeast Tine",
    "Hone Sundan",
    "Spire of Honor",
    "The Meat Scraper",
    "Blackleach Blade",
    "Athena's Wrath",
    "Pierre Tombale Couant",
    "Husoldal Evo",
    "Grim's Burning Dead",
    "Razorswitch",
    "Ribcracker",
    "Chromatic Ire",
    "Warpspear",
    "Skullcollector",
    "Skystrike",
    "Riphook",
    "Kuko Shakaku",
    "Endlesshail",
    "Whichwild String",
    "Cliffkiller",
    "Magewrath",
    "Godstrike Arch",
    "Langer Briser",
    "Pus Spiter",
    "Buriza-Do Kyanon",
    "Demon Machine",
    "Armor",
    "Peasent Crown",
    "Rockstopper",
    "Stealskull",
    "Darksight Helm",
    "Valkiry Wing",
    "Crown of Thieves",
    "Blackhorn's Face",
    "Vampiregaze",
    "The Spirit Shroud",
    "Skin of the Vipermagi",
    "Skin of the Flayerd One",
    "Ironpelt",
    "Spiritforge",
    "Crow Caw",
    "Shaftstop",
    "Duriel's Shell",
    "Skullder's Ire",
    "Guardian Angel",
    "Toothrow",
    "Atma's Wail",
    "Black Hades",
    "Corpsemourn",
    "Que-Hegan's Wisdon",
    "Visceratuant",
    "Mosers Blessed Circle",
    "Stormchaser",
    "Tiamat's Rebuke",
    "Kerke's Sanctuary",
    "Radimant's Sphere",
    "Lidless Wall",
    "Lance Guard",
    "Venom Grip",
    "Gravepalm",
    "Ghoulhide",
    "Lavagout",
    "Hellmouth",
    "Infernostride",
    "Waterwalk",
    "Silkweave",
    "Wartraveler",
    "Gorerider",
    "String of Ears",
    "Razortail",
    "Gloomstrap",
    "Snowclash",
    "Thudergod's Vigor",
    "Elite Uniques",
    "Harlequin Crest",
    "Veil of Steel",
    "The Gladiator's Bane",
    "Arkaine's Valor",
    "Blackoak Shield",
    "Stormshield",
    "Hellslayer",
    "Messerschmidt's Reaver",
    "Baranar's Star",
    "Schaefer's Hammer",
    "The Cranium Basher",
    "Lightsabre",
    "Doombringer",
    "The Grandfather",
    "Wizardspike",
    "Constricting Ring",
    "Stormspire",
    "Eaglehorn",
    "Windforce",
    "Rings",
    "Bul Katho's Wedding Band",
    "The Cat's Eye",
    "The Rising Sun",
    "Crescent Moon",
    "Mara's Kaleidoscope",
    "Atma's Scarab",
    "Dwarf Star",
    "Raven Frost",
    "Highlord's Wrath",
    "Saracen's Chance",
    "Class Specific",
    "Arreat's Face",
    "Homunculus",
    "Titan's Revenge",
    "Lycander's Aim",
    "Lycander's Flank",
    "The Oculus",
    "Herald of Zakarum",
    "Cutthroat1",
    "Jalal's Mane",
    "The Scalper",
    "Bloodmoon",
    "Djinnslayer",
    "Deathbit",
    "Warshrike",
    "Gutsiphon",
    "Razoredge",
    "Gore Ripper",
    "Demonlimb",
    "Steelshade",
    "Tomb Reaver",
    "Deaths's Web",
    "Nature's Peace",
    "Azurewrath",
    "Seraph's Hymn",
    "Zakarum's Salvation",
    "Fleshripper",
    "Odium",
    "Horizon's Tornado",
    "Stone Crusher",
    "Jadetalon",
    "Shadowdancer",
    "Cerebus",
    "Tyrael's Might",
    "Souldrain",
    "Runemaster",
    "Deathcleaver",
    "Executioner's Justice",
    "Stoneraven",
    "Leviathan",
    "Larzuk's Champion",
    "Wisp",
    "Gargoyle's Bite",
    "Lacerator",
    "Mang Song's Lesson",
    "Viperfork",
    "Ethereal Edge",
    "Demonhorn's Edge",
    "The Reaper's Toll",
    "Spiritkeeper",
    "Hellrack",
    "Alma Negra",
    "Darkforge Spawn",
    "Widowmaker",
    "Bloodraven's Charge",
    "Ghostflame",
    "Shadowkiller",
    "Gimmershred",
    "Griffon's Eye",
    "Windhammer",
    "Thunderstroke",
    "Giantmaimer",
    "Demon's Arch",
    "Boneflame",
    "Steelpillar",
    "Nightwing's Veil",
    "Crown of Ages",
    "Andariel's Visage",
    "Darkfear",
    "Dragonscale",
    "Steel Carapice",
    "Medusa's Gaze",
    "Ravenlore",
    "Boneshade",
    "Nethercrow",
    "Flamebellow",
    "Fathom",
    "Wolfhowl",
    "Spirit Ward",
    "Kira's Guardian",
    "Ormus' Robes",
    "Gheed's Fortune",
    "Stormlash",
    "Halaberd's Reign",
    "Warriv's Warder",
    "Spike Thorn",
    "Dracul's Grasp",
    "Frostwind",
    "Templar's Might",
    "Eschuta's temper",
    "Firelizard's Talons",
    "Sandstorm Trek",
    "Marrowwalk",
    "Heaven's Light",
    "Merman's Speed",
    "Arachnid Mesh",
    "Nosferatu's Coil",
    "Metalgrid",
    "Verdugo's Hearty Cord",
    "Sigurd's Staunch",
    "Carrion Wind",
    "Giantskull",
    "Ironward",
    "Annihilus",
    "Arioc's Needle",
    "Cranebeak",
    "Nord's Tenderizer",
    "Earthshifter",
    "Wraithflight",
    "Bonehew",
    "Ondal's Wisdom",
    "The Reedeemer",
    "Headhunter's Glory",
    "Steelrend",
    "Rainbow Facet",
    "Rainbow Facet",
    "Rainbow Facet",
    "Rainbow Facet",
    "Rainbow Facet",
    "Rainbow Facet",
    "Rainbow Facet",
    "Rainbow Facet",
    "Hellfire Torch",
    "Cold Rupture",
    "Flame Rift",
    "Crack of the Heavens",
    "Rotting Fissure",
    "Bone Break",
    "Black Cleft",
]

# 道具字典<Key, 模型>
ITEM_MISC = {
    "skc": "data/hd/items/misc/gem/chipped_skull.json",
    "gcy": "data/hd/items/misc/gem/chipped_topaz.json",
    "gcv": "data/hd/items/misc/gem/chipped_amethyst.json",
    "gcb": "data/hd/items/misc/gem/chipped_saphire.json",
    "gcr": "data/hd/items/misc/gem/chipped_ruby.json",
    "gcg": "data/hd/items/misc/gem/chipped_emerald.json",
    "gcw": "data/hd/items/misc/gem/chipped_diamond.json",
    "skf": "data/hd/items/misc/gem/flawed_skull.json",
    "gfy": "data/hd/items/misc/gem/flawed_topaz.json",
    "gfv": "data/hd/items/misc/gem/flawed_amethyst.json",
    "gfb": "data/hd/items/misc/gem/flawed_saphire.json",
    "gfr": "data/hd/items/misc/gem/flawed_ruby.json",
    "gfg": "data/hd/items/misc/gem/flawed_emerald.json",
    "gfw": "data/hd/items/misc/gem/flawed_diamond.json",
    "sku": "data/hd/items/misc/gem/skull.json",
    "gsy": "data/hd/items/misc/gem/topaz.json",
    "gsv": "data/hd/items/misc/gem/amethyst.json",
    "gsb": "data/hd/items/misc/gem/saphire.json",
    "gsr": "data/hd/items/misc/gem/ruby.json",
    "gsg": "data/hd/items/misc/gem/emerald.json",
    "gsw": "data/hd/items/misc/gem/diamond.json",
    "skl": "data/hd/items/misc/gem/flawless_skull.json",
    "gly": "data/hd/items/misc/gem/flawless_topaz.json",
    "gzv": "data/hd/items/misc/gem/flawless_amethyst.json",
    "glb": "data/hd/items/misc/gem/flawless_saphire.json",
    "glr": "data/hd/items/misc/gem/flawless_ruby.json",
    "glg": "data/hd/items/misc/gem/flawless_emerald.json",
    "glw": "data/hd/items/misc/gem/flawless_diamond.json",
    "skz": "data/hd/items/misc/gem/perfect_skull.json",
    "gpy": "data/hd/items/misc/gem/perfect_topaz.json",
    "gpv": "data/hd/items/misc/gem/perfect_amethyst.json",
    "gpb": "data/hd/items/misc/gem/perfect_saphire.json",
    "gpr": "data/hd/items/misc/gem/perfect_ruby.json",
    "gpg": "data/hd/items/misc/gem/perfect_emerald.json",
    "gpw": "data/hd/items/misc/gem/perfect_diamond.json",
    "r01": "data/hd/items/misc/rune/el_rune.json",
    "r02": "data/hd/items/misc/rune/eld_rune.json",
    "r03": "data/hd/items/misc/rune/tir_rune.json",
    "r04": "data/hd/items/misc/rune/nef_rune.json",
    "r05": "data/hd/items/misc/rune/eth_rune.json",
    "r06": "data/hd/items/misc/rune/ith_rune.json",
    "r07": "data/hd/items/misc/rune/tal_rune.json",
    "r08": "data/hd/items/misc/rune/ral_rune.json",
    "r09": "data/hd/items/misc/rune/ort_rune.json",
    "r10": "data/hd/items/misc/rune/thul_rune.json",
    "r11": "data/hd/items/misc/rune/amn_rune.json",
    "r12": "data/hd/items/misc/rune/sol_rune.json",
    "r13": "data/hd/items/misc/rune/shael_rune.json",
    "r14": "data/hd/items/misc/rune/dol_rune.json",
    "r15": "data/hd/items/misc/rune/hel_rune.json",
    "r16": "data/hd/items/misc/rune/io_rune.json",
    "r17": "data/hd/items/misc/rune/lum_rune.json",
    "r18": "data/hd/items/misc/rune/ko_rune.json",
    "r19": "data/hd/items/misc/rune/fal_rune.json",
    "r20": "data/hd/items/misc/rune/lem_rune.json",
    "r21": "data/hd/items/misc/rune/pul_rune.json",
    "r22": "data/hd/items/misc/rune/um_rune.json",
    "r23": "data/hd/items/misc/rune/mal_rune.json",
    "r24": "data/hd/items/misc/rune/ist_rune.json",
    "r25": "data/hd/items/misc/rune/gul_rune.json",
    "r26": "data/hd/items/misc/rune/vex_rune.json",
    "r27": "data/hd/items/misc/rune/ohm_rune.json",
    "r28": "data/hd/items/misc/rune/lo_rune.json",
    "r29": "data/hd/items/misc/rune/sur_rune.json",
    "r30": "data/hd/items/misc/rune/ber_rune.json",
    "r31": "data/hd/items/misc/rune/jah_rune.json",
    "r32": "data/hd/items/misc/rune/cham_rune.json",
    "r33": "data/hd/items/misc/rune/zod_rune.json",
    "hp1": "data/hd/items/misc/potion/lesser_healing_potion.json",
    "hp2": "data/hd/items/misc/potion/light_healing_potion.json",
    "hp3": "data/hd/items/misc/potion/healing_potion2.json",
    "hp4": "data/hd/items/misc/potion/strong_healing_potion.json",
    "hp5": "data/hd/items/misc/potion/greater_healing_potion.json",
    "mp1": "data/hd/items/misc/potion/lesser_mana_potion.json",
    "mp2": "data/hd/items/misc/potion/light_mana_potion.json",
    "mp3": "data/hd/items/misc/potion/mana_potion2.json",
    "mp4": "data/hd/items/misc/potion/strong_mana_potion.json",
    "mp5": "data/hd/items/misc/potion/greater_mana_potion.json",
    "gpl": "data/hd/items/weapon/potion/choking_gas_potion.json",
    "gpm": "data/hd/items/weapon/potion/rancid_gas_potion.json",
    "gps": "data/hd/items/weapon/potion/strangling_gas_potion.json",
    "opl": "data/hd/items/weapon/potion/exploding_potion.json",
    "opm": "data/hd/items/weapon/potion/fulminating_potion.json",
    "ops": "data/hd/items/weapon/potion/oil_potion.json",
    "vps": "data/hd/items/misc/potion/stamina_potion.json",
    "yps": "data/hd/items/misc/potion/antidote_potion.json",
    "wms": "data/hd/items/misc/potion/thawing_potion.json",
    "rvs": "data/hd/items/misc/potion/rejuv_potion.json",
    "rvl": "data/hd/items/misc/potion/full_rejuv_potion.json",
    "aqv": "data/hd/items/misc/quiver/arrows.json",
    "cqv": "data/hd/items/misc/quiver/bolts.json",
    "tsc": "data/hd/items/misc/scroll/town_portal_scroll.json",
    "isc": "data/hd/items/misc/scroll/identify_scroll.json",
    "key": "data/hd/items/misc/key/skeleton_key.json",
    "cm1": "data/hd/items/misc/charm/charm_small.json",
    "cm2": "data/hd/items/misc/charm/charm_medium.json",
    "cm3": "data/hd/items/misc/charm/charm_large.json",
    "jew": "data/hd/items/misc/jewel/jewel.json",
    "gds": "data/hd/items/misc/gold/gold_small.json",
    "gdm": "data/hd/items/misc/gold/gold_medium.json",
    "gdl": "data/hd/items/misc/gold/gold_large.json",
    "gdx": "data/hd/items/misc/gold/gold_xlarge.json",
}

# 自定义声音
CUSTOM_SOUNDS = {
    # Item
    "sc":                 {True: r"item\sc.flac",                  False: r"item\item_charm_hd.flac",   "path": "data/hd/global/sfx/item/sc.flac"},
    "lc":                 {True: r"item\lc.flac",                  False: r"item\item_charm_hd.flac",   "path": "data/hd/global/sfx/item/lc.flac"},  
    "gc":                 {True: r"item\gc.flac",                  False: r"item\item_charm_hd.flac",   "path": "data/hd/global/sfx/item/gc.flac"},
    "r01":                {True: r"item\r01.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r31.flac"},
    "r02":                {True: r"item\r02.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r32.flac"},
    "r03":                {True: r"item\r03.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r33.flac"},
    "r04":                {True: r"item\r04.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r24.flac"},
    "r05":                {True: r"item\r05.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r25.flac"},
    "r06":                {True: r"item\r06.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r26.flac"},
    "r07":                {True: r"item\r07.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r27.flac"},
    "r08":                {True: r"item\r08.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r28.flac"},
    "r09":                {True: r"item\r09.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r29.flac"},
    "r10":                {True: r"item\r10.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r30.flac"},
    "r11":                {True: r"item\r11.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r31.flac"},
    "r12":                {True: r"item\r12.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r32.flac"},
    "r13":                {True: r"item\r13.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r33.flac"},
    "r14":                {True: r"item\r14.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r24.flac"},
    "r15":                {True: r"item\r15.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r25.flac"},
    "r16":                {True: r"item\r16.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r26.flac"},
    "r17":                {True: r"item\r17.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r27.flac"},
    "r18":                {True: r"item\r18.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r28.flac"},
    "r19":                {True: r"item\r19.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r29.flac"},
    "r20":                {True: r"item\r20.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r30.flac"},
    "r21":                {True: r"item\r21.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r31.flac"},
    "r22":                {True: r"item\r22.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r32.flac"},
    "r23":                {True: r"item\r23.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r33.flac"},
    "r24":                {True: r"item\r24.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r24.flac"},
    "r25":                {True: r"item\r25.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r25.flac"},
    "r26":                {True: r"item\r26.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r26.flac"},
    "r27":                {True: r"item\r27.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r27.flac"},
    "r28":                {True: r"item\r28.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r28.flac"},
    "r29":                {True: r"item\r29.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r29.flac"},
    "r30":                {True: r"item\r30.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r30.flac"},
    "r31":                {True: r"item\r31.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r31.flac"},
    "r32":                {True: r"item\r32.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r32.flac"},
    "r33":                {True: r"item\r33.flac",                 False: r"item\item_rune_hd.flac",    "path": "data/hd/global/sfx/item/r33.flac"},
    "rin":                {True: r"item\rin.flac",                 False: r"item\item_ring_hd.flac",    "path": "data/hd/global/sfx/item/rin.flac"},
    "amu":                {True: r"item\amu.flac",                 False: r"item\item_amulet_hd.flac",  "path": "data/hd/global/sfx/item/amu.flac"},
    "jew":                {True: r"item\jew.flac",                 False: r"item\item_jewel_hd.flac",   "path": "data/hd/global/sfx/item/jew.flac"},
    "diadem":             {True: r"item\diadem.flac",              False: r"item\item_helm_hd.flac",    "path": "data/hd/global/sfx/item/diadem.flac"},
    "mephisto_key":       {True: r"item\torch_key.flac",           False: r"item\item_key_hd.flac",     "path": "data/hd/global/sfx/item/mephisto_key.flac"},
    # Skill
    "enchant_off":        {True: r"skill\enchant_off.flac",        False: r"none.flac",                 "path": "data/hd/global/sfx/skill/enchant_off.flac"},
    "chillingarmor_off":  {True: r"skill\chillingarmor_off.flac",  False: r"none.flac",                 "path": "data/hd/global/sfx/skill/chillingarmor_off.flac"},
    "shout_off":          {True: r"skill\shout_off.flac",          False: r"none.flac",                 "path": "data/hd/global/sfx/skill/shout_off.flac"},
    "energyshield_off":   {True: r"skill\energyshield_off.flac",   False: r"none.flac",                 "path": "data/hd/global/sfx/skill/energyshield_off.flac"},
    "venom_off":          {True: r"skill\venom_off.flac",          False: r"none.flac",                 "path": "data/hd/global/sfx/skill/venom_off.flac"},
    "battleorders_off":   {True: r"skill\battleorders_off.flac",   False: r"none.flac",                 "path": "data/hd/global/sfx/skill/battleorders_off.flac"},
    "battlecommand_off":  {True: r"skill\battlecommand_off.flac",  False: r"none.flac",                 "path": "data/hd/global/sfx/skill/battlecommand_off.flac"},
    "shiverarmor_off":    {True: r"skill\shiverarmor_off.flac",    False: r"none.flac",                 "path": "data/hd/global/sfx/skill/shiverarmor_off.flac"},
    "holyshield_off":     {True: r"skill\holyshield_off.flac",     False: r"none.flac",                 "path": "data/hd/global/sfx/skill/holyshield_off.flac"},
    "cyclonearmor_off":   {True: r"skill\cyclonearmor_off.flac",   False: r"none.flac",                 "path": "data/hd/global/sfx/skill/cyclonearmor_off.flac"},
    "quickness_off":      {True: r"skill\quickness_off.flac",      False: r"none.flac",                 "path": "data/hd/global/sfx/skill/quickness_off.flac"},
    "bladeshield_off":    {True: r"skill\bladeshield_off",         False: r"none.flac",                 "path": "data/hd/global/sfx/skill/bladeshield_off.flac"},
    "wolf_off":           {True: r"skill\wolf_off.flac",           False: r"none.flac",                 "path": "data/hd/global/sfx/skill/wolf_off.flac"},
    "bear_off":           {True: r"skill\bear_off.flac",           False: r"none.flac",                 "path": "data/hd/global/sfx/skill/bear_off.flac"},
    "frozenarmor_off":    {True: r"skill\frozenarmor_off.flac",    False: r"none.flac",                 "path": "data/hd/global/sfx/skill/frozenarmor_off.flac"},
    "bonearmor_off":      {True: r"skill\bonearmor_off.flac",      False: r"none.flac",                 "path": "data/hd/global/sfx/skill/bonearmor_off.flac"},
    "markwolf_off":       {True: r"skill\markwolf_off.flac",       False: r"none.flac",                 "path": "data/hd/global/sfx/skill/markwolf_off.flac"},
    "markbear_off":       {True: r"skill\markbear_off.flac",       False: r"none.flac",                 "path": "data/hd/global/sfx/skill/markbear_off.flac"},
    "fade_off":           {True: r"skill\fade_off.flac",           False: r"none.flac",                 "path": "data/hd/global/sfx/skill/fade_off.flac"},
    # Mercenaries
    "guard_death_hd1":    {True: r"monster\rogue\death1_hd.flac",  False: r"monster\guard\monster_guard_death_1_hd.flac",                 "path": ""},
    "guard_death_hd2":    {True: r"monster\rogue\death2_hd.flac",  False: r"monster\guard\monster_guard_death_2_hd.flac",                 "path": ""},
    "guard_death_hd3":    {True: r"monster\rogue\death1_hd.flac",  False: r"monster\guard\monster_guard_death_3_hd.flac",                 "path": ""},
    "guard_hit_hd1":      {True: r"monster\rogue\gethit1_hd.flac", False: r"monster\guard\monster_guard_gethit_1_hd.flac",                 "path": ""},
    "guard_hit_hd2":      {True: r"monster\rogue\gethit2_hd.flac", False: r"monster\guard\monster_guard_gethit_2_hd.flac",                 "path": ""},
    "guard_hit_hd3":      {True: r"monster\rogue\gethit3_hd.flac", False: r"monster\guard\monster_guard_gethit_3_hd.flac",                 "path": ""},
    "guard_hit_hd4":      {True: r"monster\rogue\gethit4_hd.flac", False: r"monster\guard\monster_guard_gethit_4_hd.flac",                 "path": ""},
}


# 导出所有需要的符号
__all__ = [
    'MUTEX_NAME',
    'ERROR_ALREADY_EXISTS',
    'WM_SHOW_WINDOW',
    'ZHCN',
    'ZHCN2',
    'ZHTW',
    'ZHTW2',
    'ZHSGCN',
    'ZHSGTW',
    'ENUS',
    'LANGUAGES',
    'UI_PANEL_HEALTH',
    'UI_PANEL_MANA',
    'APP_NAME',
    'APP_VERSION',
    'APP_FULL_NAME',
    'APP_DATE',
    'APP_SIZE',
    'NETEASE_LANGUAGE',
    'BATTLE_NET_LANGUAGE',
    'TERROR_ZONE_SERVER',
    'TERROR_ZONE_LANGUAGE',
    'TERROR_ZONE_NEXT',
    'TERROR_ZONE_TABLE',
    'GOLD_NAMES',
    'GAME_SETTING',
    'GAME_SETTING2',
    'GAME_SETTING3',
    'CONTROLS_SETTING',
    'LIGHT_REDIUS',
    'HUD_SIZE',
    'PORTAL_SKIN',
    'CHARACTER_EFFECTS',
    'ARROW',
    'SOR_SETTING',
    'TELEPORT_SKIN',
    'NEC_SETTING',
    'PAL_SETTING',
    'BAR_SETTING',
    'DRU_SETTING',
    'ASN_SETTING',
    'ASN_MARTIAL',
    'COMMON_SETTING',
    'SKILL_OFF_SOUNDS',
    'MERCENARY',
    'MERCENARY_LOCATION',
    'MERCENARY_100',
    'MERCENARY_85',
    'MERCENARY_75',
    'MERCENARY_65',
    'MONSTER_SETTING',
    'MONSTER_LIGHTING',
    'MONSTER_HEALTH',
    'MONSTER_MISSILE',
    'BASE_EFFECTS',
    'EQIUPMENT_SETTING',
    'AFFIX_EFFECTS',
    'UNIQUE_EFFECTS',
    'SETS_EFFECTS',
    'UNIQUE_COLOR',
    'MODEL_EFFECTS',
    'RUNE_SIZE',
    'ITEM_NOTIFICATION',
    'ITEM_RUNE_SETTING1',
    'ITEM_RUNE_SETTING2',
    'ASSET_PATH',
    'ITEM_ENUS',
    'ITEM_ZHTW',
    'LNG_STRINGS',
    'TORCH_KEY',
    'ITEM_FILTER',
    'DISABLE_EFFECTS',
    'ENABLE_POINTER',
    'RADIO',
    'CHECK',
    'SPIN',
    'LOCATION',
    'SEPARATOR',
    'REGION_DOMAIN_MAP',
    'REGION_NAME_MAP',
    'UE01A',
    'TERROR_ZONE_API',
    'TERROR_ZONE_DICT',
    'TERROR_ZONE_MAP',
    'SETS_INDEX',
    'SET_ITEM_INDEX',
    'ITEM_BASE',
    'ITEM_UNIQUE',
    'ITEM_MISC',
    'CUSTOM_SOUNDS',
    'WAYPOINT_POINTER',
    'MISSION_POINTER',
    'UPSTAIRS_POINTER',
    'DOWNSTAIRS_POINTER',
    'NEXTAREA_POINTER',
    'MINI_CUBE',
    'ESC_SETTING',
    'GAME_MODEL',
    'RUNE_SKIN',
    'SKILL_SKIN',
    'FONT_TYPE',
    'ACT1_HIRE',
    'ACT2_HIRE',
    'ACT3_HIRE',
    'ACT5_HIRE',
    'HUD_SKIN',
    'OTHERS',
    'TOA',
    'AMA',
    'SOR',
    'NEC',
    'PAL',
    'BAR',
    'DRU',
    'ASN',
    'APPLY_METHOD',
    'REMOVE_METHOD',
    'GAME_MODEL_APPLY',
    'HIRE_SKIN_APPLY',
    'HIRE_SKIN_REMOVE',
    'init_global_dict',
    'translate',
]